<?php
namespace App\Console\Commands\DomainChecker;


class ServerMapping
{
    private $mapping;

    function __construct()
    {
        $this->mapping = $this->prepareMapping([
            "Registrar Registration Expiration Date" => 'expiry',
            "Registry Expiry Date" => 'expiry',
            "Creation Date" => "registration_date",
            "Registrar WHOIS Server" => "whois_server",
        ]);
    }

    /**
     * Maps server key to normalised key
     *
     * @param $server
     * @param $key
     * @return null | string
     */
    public function mapKey($server, $key) {
        // Check if server exists
        if (!isset($this->mapping[$server])) {
            return null;
        }

        // Check if key exists for server
        if (!isset($this->mapping[$server][$key])) {
            return null;
        }

        return $this->mapping[$server][$key];
    }

    /**
     * Checks if we have mappings for server
     *
     * @param $server
     * @return bool
     */
    public function hasServer($server) {
        // Check if server exists
        return isset($this->mapping[$server]);
    }

    /**
     * Array of key mappings for all WHOIS servers
     *
     * Normalised values are:
     * WHOIS Server
     * Expiry Date
     * Creation Date
     *
     * @param $default_mapping
     * @return array
     */
    private function prepareMapping($default_mapping)
    {
        return [
            "capetown-whois.registry.net.za" => $default_mapping,
            "ccwhois.ksregistry.net" => $default_mapping,
            "ccwhois.verisign-grs.com" => $default_mapping,
            "cwhois.cnnic.cn" => $default_mapping,
            "domain-registry-whois.l.google.com" => $default_mapping,
            "durban-whois.registry.net.za" => $default_mapping,
            "jobswhois.verisign-grs.com" => $default_mapping,
            "joburg-whois.registry.net.za" => $default_mapping,
            "kero.yachay.pe" => $default_mapping,
            "tvwhois.verisign-grs.com" => $default_mapping,
            "vunic.vu" => $default_mapping,
            "whois-alsace.nic.fr" => $default_mapping,
            "whois-bzh.nic.fr" => $default_mapping,
            "whois-cl01.mm-registry.com" => $default_mapping,
            "whois-dub.mm-registry.com" => $default_mapping,
            "whois-fe1.gmx.tango.knipp.de" => $default_mapping,
            "whois-fe1.pdt.cologne.tango.knipp.de" => $default_mapping,
            "whois-fe1.pdt.koeln.tango.knipp.de" => $default_mapping,
            "whois-frogans.nic.fr" => $default_mapping,
            "whois-lon.mm-registry.com" => $default_mapping,
            "whois-ovh.nic.fr" => $default_mapping,
            "whois-paris.nic.fr" => $default_mapping,
            "whois.aeda.net.ae" => $default_mapping,
            "whois.aero" => $default_mapping,
            "whois.afilias-srs.net" => $default_mapping,
            "whois.afilias.net" => $default_mapping,
            "whois.ai" => $default_mapping,
            "whois.amnic.net" => $default_mapping,
            "whois.aridnrs.net.au" => $default_mapping,
            "whois.arnes.si" => $default_mapping,
            "whois.ati.tn" => $default_mapping,
            "whois.audns.net.au" => $default_mapping,
            "whois.ax" => $default_mapping,
            "whois.bazaar.coreregistry.net" => $default_mapping,
            "whois.belizenic.bz" => $default_mapping,
            "whois.biz" => $default_mapping,
            "whois.bn" => $default_mapping,
            "whois.cat" => $default_mapping,
            "whois.cctld.by" => $default_mapping,
            "whois.cctld.uz" => $default_mapping,
            "whois.centralnic.com" => $default_mapping,
            "whois.channelisles.net" => $default_mapping,
            "whois.cira.ca" => $default_mapping,
            "whois.cmc.iq" => $default_mapping,
            "whois.cnnic.net.cn" => $default_mapping,
            "whois.co" => $default_mapping,
            "whois.co.ug" => $default_mapping,
            "whois.conac.cn" => $default_mapping,
            "whois.denic.de" => $default_mapping,
            "whois.dk-hostmaster.dk" => $default_mapping,
            "whois.dns.be" => $default_mapping,
            "whois.dns.hr" => $default_mapping,
            "whois.dns.lu" => $default_mapping,
            "whois.dns.pl" => $default_mapping,
            "whois.dns.pt" => $default_mapping,
            "whois.domain-registry.nl" => $default_mapping,
            "whois.domainregistry.ie" => $default_mapping,
            "whois.dominio.gq" => $default_mapping,
            "whois.domreg.lt" => $default_mapping,
            "whois.donuts.co" => $default_mapping,
            "whois.dot.cf" => $default_mapping,
            "whois.dot.ml" => $default_mapping,
            "whois.dot.tk" => $default_mapping,
            "whois.dotmobiregistry.net" => $default_mapping,
            "whois.dotpostregistry.net" => $default_mapping,
            "whois.dotukr.com" => $default_mapping,
            "whois.educause.edu" => $default_mapping,
            "whois.eenet.ee" => $default_mapping,
            "whois.eu" => $default_mapping,
            "whois.eus.coreregistry.net" => $default_mapping,
            "whois.ficora.fi" => $default_mapping,
            "whois.gal.coreregistry.net" => $default_mapping,
            "whois.godaddy.com" => $default_mapping,
            "whois.gtld.knet.cn" => $default_mapping,
            "whois.gtlds.nic.br" => $default_mapping,
            "whois.hkirc.hk" => $default_mapping,
            "whois.iam.net.ma" => $default_mapping,
            "whois.iana.org" => $default_mapping,
            "whois.iis.se" => $default_mapping,
            "whois.inregistry.net" => $default_mapping,
            "whois.internic.net" => $default_mapping,
            "whois.isnic.is" => $default_mapping,
            "whois.isoc.org.il" => $default_mapping,
            "whois.jprs.jp" => $default_mapping,
            "whois.kenic.or.ke" => $default_mapping,
            "whois.kr" => $default_mapping,
            "whois.ksregistry.net" => $default_mapping,
            "whois.mango.coreregistry.net" => $default_mapping,
            "whois.marnet.mk" => $default_mapping,
            "whois.meridiantld.net" => $default_mapping,
            "whois.monic.mo" => $default_mapping,
            "whois.museum" => $default_mapping,
            "whois.mx" => $default_mapping,
            "whois.mynic.my" => $default_mapping,
            "whois.na-nic.com.na" => $default_mapping,
            "whois.nc" => $default_mapping,
            "whois.netnames.net" => $default_mapping,
            "whois.ngtld.cn" => $default_mapping,
            "whois.nic.ac" => $default_mapping,
            "whois.nic.ae" => $default_mapping,
            "whois.nic.af" => $default_mapping,
            "whois.nic.ag" => $default_mapping,
            "whois.nic.as" => $default_mapping,
            "whois.nic.asia" => $default_mapping,
            "whois.nic.at" => $default_mapping,
            "whois.nic.aw" => $default_mapping,
            "whois.nic.bar" => $default_mapping,
            "whois.nic.berlin" => $default_mapping,
            "whois.nic.best" => $default_mapping,
            "whois.nic.bi" => $default_mapping,
            "whois.nic.bj" => $default_mapping,
            "whois.nic.bo" => $default_mapping,
            "whois.nic.br" => $default_mapping,
            "whois.nic.brussels" => $default_mapping,
            "whois.nic.build" => $default_mapping,
            "whois.nic.cancerresearch" => $default_mapping,
            "whois.nic.career" => $default_mapping,
            "whois.nic.cd" => $default_mapping,
            "whois.nic.ceo" => $default_mapping,
            "whois.nic.ch" => $default_mapping,
            "whois.nic.ci" => $default_mapping,
            "whois.nic.ck" => $default_mapping,
            "whois.nic.cl" => $default_mapping,
            "whois.nic.club" => $default_mapping,
            "whois.nic.coop" => $default_mapping,
            "whois.nic.cuisinella" => $default_mapping,
            "whois.nic.cx" => $default_mapping,
            "whois.nic.cymru" => $default_mapping,
            "whois.nic.cz" => $default_mapping,
            "whois.nic.dm" => $default_mapping,
            "whois.nic.dz" => $default_mapping,
            "whois.nic.ec" => $default_mapping,
            "whois.nic.es" => $default_mapping,
            "whois.nic.fo" => $default_mapping,
            "whois.nic.fr" => $default_mapping,
            "whois.nic.frl" => $default_mapping,
            "whois.nic.gd" => $default_mapping,
            "whois.nic.gent" => $default_mapping,
            "whois.nic.gl" => $default_mapping,
            "whois.nic.gov" => $default_mapping,
            "whois.nic.gs" => $default_mapping,
            "whois.nic.hamburg" => $default_mapping,
            "whois.nic.hn" => $default_mapping,
            "whois.nic.host" => $default_mapping,
            "whois.nic.ht" => $default_mapping,
            "whois.nic.hu" => $default_mapping,
            "whois.nic.ibm" => $default_mapping,
            "whois.nic.im" => $default_mapping,
            "whois.nic.io" => $default_mapping,
            "whois.nic.ir" => $default_mapping,
            "whois.nic.it" => $default_mapping,
            "whois.nic.ki" => $default_mapping,
            "whois.nic.kiwi" => $default_mapping,
            "whois.nic.kz" => $default_mapping,
            "whois.nic.la" => $default_mapping,
            "whois.nic.lacaixa" => $default_mapping,
            "whois.nic.li" => $default_mapping,
            "whois.nic.love" => $default_mapping,
            "whois.nic.luxury" => $default_mapping,
            "whois.nic.lv" => $default_mapping,
            "whois.nic.ly" => $default_mapping,
            "whois.nic.md" => $default_mapping,
            "whois.nic.me" => $default_mapping,
            "whois.nic.menu" => $default_mapping,
            "whois.nic.mg" => $default_mapping,
            "whois.nic.mn" => $default_mapping,
            "whois.nic.moe" => $default_mapping,
            "whois.nic.monash" => $default_mapping,
            "whois.nic.moscow" => $default_mapping,
            "whois.nic.mp" => $default_mapping,
            "whois.nic.ms" => $default_mapping,
            "whois.nic.mu" => $default_mapping,
            "whois.nic.mz" => $default_mapping,
            "whois.nic.name" => $default_mapping,
            "whois.nic.net.bw" => $default_mapping,
            "whois.nic.net.ng" => $default_mapping,
            "whois.nic.net.sa" => $default_mapping,
            "whois.nic.net.sb" => $default_mapping,
            "whois.nic.net.sg" => $default_mapping,
            "whois.nic.nf" => $default_mapping,
            "whois.nic.nrw" => $default_mapping,
            "whois.nic.nu" => $default_mapping,
            "whois.nic.one" => $default_mapping,
            "whois.nic.ooo" => $default_mapping,
            "whois.nic.org.uy" => $default_mapping,
            "whois.nic.physio" => $default_mapping,
            "whois.nic.pm" => $default_mapping,
            "whois.nic.pr" => $default_mapping,
            "whois.nic.press" => $default_mapping,
            "whois.nic.pro" => $default_mapping,
            "whois.nic.pw" => $default_mapping,
            "whois.nic.re" => $default_mapping,
            "whois.nic.reise" => $default_mapping,
            "whois.nic.ruhr" => $default_mapping,
            "whois.nic.scb" => $default_mapping,
            "whois.nic.schmidt" => $default_mapping,
            "whois.nic.sh" => $default_mapping,
            "whois.nic.sm" => $default_mapping,
            "whois.nic.sn" => $default_mapping,
            "whois.nic.so" => $default_mapping,
            "whois.nic.space" => $default_mapping,
            "whois.nic.st" => $default_mapping,
            "whois.nic.store" => $default_mapping,
            "whois.nic.tatar" => $default_mapping,
            "whois.nic.tel" => $default_mapping,
            "whois.nic.tf" => $default_mapping,
            "whois.nic.tirol" => $default_mapping,
            "whois.nic.tj" => $default_mapping,
            "whois.nic.tl" => $default_mapping,
            "whois.nic.tm" => $default_mapping,
            "whois.nic.top" => $default_mapping,
            "whois.nic.tr" => $default_mapping,
            "whois.nic.travel" => $default_mapping,
            "whois.nic.uk" => $default_mapping,
            "whois.nic.us" => $default_mapping,
            "whois.nic.ve" => $default_mapping,
            "whois.nic.versicherung" => $default_mapping,
            "whois.nic.vlaanderen" => $default_mapping,
            "whois.nic.wales" => $default_mapping,
            "whois.nic.website" => $default_mapping,
            "whois.nic.wed" => $default_mapping,
            "whois.nic.wf" => $default_mapping,
            "whois.nic.wien" => $default_mapping,
            "whois.nic.wiki" => $default_mapping,
            "whois.nic.wtc" => $default_mapping,
            "whois.nic.xn--80adxhks" => $default_mapping,
            "whois.nic.xn--d1acj3b" => $default_mapping,
            "whois.nic.xn--ngbc5azd" => $default_mapping,
            "whois.nic.xn--p1acf" => $default_mapping,
            "whois.nic.xxx" => $default_mapping,
            "whois.nic.xyz" => $default_mapping,
            "whois.nic.yt" => $default_mapping,
            "whois.nic.zm" => $default_mapping,
            "whois.norid.no" => $default_mapping,
            "whois.online.rs.corenic.net" => $default_mapping,
            "whois.pandi.or.id" => $default_mapping,
            "whois.pir.org" => $default_mapping,
            "whois.publicinterestregistry.net" => $default_mapping,
            "whois.quebec.rs.corenic.net" => $default_mapping,
            "whois.register.bg" => $default_mapping,
            "whois.registry.gy" => $default_mapping,
            "whois.registry.om" => $default_mapping,
            "whois.registry.pf" => $default_mapping,
            "whois.registry.qa" => $default_mapping,
            "whois.rightside.co" => $default_mapping,
            "whois.ripe.net" => $default_mapping,
            "whois.ripn.net" => $default_mapping,
            "whois.rnids.rs" => $default_mapping,
            "whois.rotld.ro" => $default_mapping,
            "whois.scot.coreregistry.net" => $default_mapping,
            "whois.sgnic.sg" => $default_mapping,
            "whois.site.rs.corenic.net" => $default_mapping,
            "whois.sk-nic.sk" => $default_mapping,
            "whois.srs.net.nz" => $default_mapping,
            "whois.sx" => $default_mapping,
            "whois.tcinet.ru" => $default_mapping,
            "whois.thnic.co.th" => $default_mapping,
            "whois.tld.sy" => $default_mapping,
            "whois.tonic.to" => $default_mapping,
            "whois.twnic.net.tw" => $default_mapping,
            "whois.tznic.or.tz" => $default_mapping,
            "whois.ua" => $default_mapping,
            "whois.uniregistry.net" => $default_mapping,
            "whois.unitedtld.com" => $default_mapping,
            "whois.verisign-grs.com" => $default_mapping,
            "whois.verisign-grs.net" => $default_mapping,
            "whois.voting.tld-box.at" => $default_mapping,
            "whois.website.ws" => $default_mapping,
            "whois2.afilias-grs.net" => $default_mapping,
            "www.domain.kg" => $default_mapping,
        ];
    }
}